apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reviews-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/proxyvert/canary-demo.git
    targetRevision: HEAD
    path: apps/reviews-app
  destination:
    server: https://kubernetes.default.svc
    namespace: reviews
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
