apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-vs
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews-stable
        subset: stable
      weight: 100
    - destination:
        host: reviews-canary
        subset: canary
      weight: 0
